services:
    my.inject_context_config:
        class: BisonLab\CommonBundle\EventListener\InsertConfigIntoEntitiesListener
        calls:
            - [ setContainer, ['@service_container'] ]
        tags:
            - { name: doctrine.event_listener, event: postLoad  }
            - { name: doctrine.event_listener, event: prePersist  }

    external_retriever:
        class: BisonLab\CommonBundle\Service\ExternalRetriever
        public: true
        arguments: ['@service_container' ]

    twig.extension.pretty_print:
        class: BisonLab\CommonBundle\Extension\TwigExtensionPrettyPrint
        public: true
        tags:
            - { name: 'twig.extension' }

    my.validator.twigvalidator:
        class: BisonLab\CommonBundle\Form\Validator\TwigValidatorService
        public: true
        tags:
            - { name: 'validator.constraint_validator' }
        arguments: ['@twig' ]

#    twig.extension.csv2html:
#        class: BisonLab\CommonBundle\Extension\TwigExtensionCsv2Html
#        public: true
#        tags:
#            - { name: 'twig.extension' }


