#services:
#    BisonLab\CommonBundle\Command\:
#        resource: '../Command/*'
#        autowire: true
#        tags: ['console.command']

# There is nothing left to control.
#    BisonLab\CommonBundle\Controller\:
#        resource: '../Controller/*'
#        tags: ['controller.service_arguments']
#        # AbstractController still needs this!
#        calls:
#            - [ setContainer, ['@service_container'] ]

    twig.extension.pretty_print:
        class: BisonLab\CommonBundle\Extension\TwigExtensionPrettyPrint
        public: true
        tags:
            - { name: 'twig.extension' }

    my.validator.twigvalidator:
        class: BisonLab\CommonBundle\Form\Validator\TwigValidatorService
        public: true
        tags:
            - { name: 'validator.constraint_validator' }
        arguments: ['@twig']

#    twig.extension.csv2html:
#        class: BisonLab\CommonBundle\Extension\TwigExtensionCsv2Html
#        public: true
#        tags:
#            - { name: 'twig.extension' }
